import { error } from '@sveltejs/kit'
import { base } from '$app/paths';

const mdModules = import.meta.glob('../../../content/org-pages/*.md');
const svxModules = import.meta.glob('../../../content/org-pages/*.svx');

export const prerender = true;

export const load = async ({ params, fetch }) => {
        if (!params || !params?.page) {
                return error(404, new Error('Post not found'));
        }

        const mdKey = `../../../content/org-pages/${params.page}.md`;
        const svxKey = `../../../content/org-pages/${params.page}.svx`;

        let post;
        let isSvx = false;

        if (mdModules[mdKey]) {
                post = await mdModules[mdKey]();
                isSvx = false;
        } else if (svxModules[svxKey]) {
                post = await svxModules[svxKey]();
                isSvx = true;
        } else {
                return error(404, new Error('Post not found'));
        }

        // Relations in both directions, generated by deploy/md_to_json.py
        const relations = await fetch(`${base}/data/relations.json`)
                .then((r) => (r.ok ? r.json() : {}))
                .catch(() => ({}));

        return {
                PostContent: post.default,
                relations: relations[post.metadata.id] || { out: [], in: [] },
                meta: { 
                        isSvx,
                        ...post.metadata, 
                        slug: params.post, 
                }
        }
}
